# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\"\x1e\n\x0bNumberArray\x12\x0f\n\x07numbers\x18\x01 \x03(\x05\"/\n\ntheJokeReq\x12\x11\n\tpunchline\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"\x1f\n\x0ctheJokeReply\x12\x0f\n\x07message\x18\x01 \x01(\t2C\n\x14NumberSortingService\x12+\n\x0bSortNumbers\x12\x0c.NumberArray\x1a\x0c.NumberArray\"\x00\x32\x35\n\tUrMumJoke\x12(\n\x08TellJoke\x12\x0b.theJokeReq\x1a\r.theJokeReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NUMBERARRAY']._serialized_start=18
  _globals['_NUMBERARRAY']._serialized_end=48
  _globals['_THEJOKEREQ']._serialized_start=50
  _globals['_THEJOKEREQ']._serialized_end=97
  _globals['_THEJOKEREPLY']._serialized_start=99
  _globals['_THEJOKEREPLY']._serialized_end=130
  _globals['_NUMBERSORTINGSERVICE']._serialized_start=132
  _globals['_NUMBERSORTINGSERVICE']._serialized_end=199
  _globals['_URMUMJOKE']._serialized_start=201
  _globals['_URMUMJOKE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
